const DEFAULT_METHOD = "single";
const DEFAULT_CHUNK_SIZE_LIMIT = 4000;

const DELIMITER_TOKEN = "__BG3_TRANSLATOR_SEGMENT_9f2b4e__";
const DELIMITER = `\n${DELIMITER_TOKEN}\n`;

const MARKUP_OR_PLACEHOLDER_SPLIT_REGEX = /(<(?!\/?LSTag\b)[A-Za-z][^>]*>|\[\d+\])/gi;
const MARKUP_TOKEN_REGEX = /^<(?!\/?LSTag\b)[A-Za-z][^>]*>$/i;
const PLACEHOLDER_TOKEN_REGEX = /^\[\d+\]$/;

module.exports = {
  DEFAULT_METHOD,
  DEFAULT_CHUNK_SIZE_LIMIT,
  DELIMITER_TOKEN,
  DELIMITER,
  MARKUP_OR_PLACEHOLDER_SPLIT_REGEX,
  MARKUP_TOKEN_REGEX,
  PLACEHOLDER_TOKEN_REGEX,
};
